import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { and, desc, eq } from 'drizzle-orm';
import { db, agentOutputsTable, type AgentOutput } from '@workspace/db';
import { marked } from 'marked';
import DOMPurify from 'isomorphic-dompurify';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CONTENT_DIR = path.resolve(__dirname, '../../content/funds');

export type WorkProductType = 'weekly-memo' | 'monthly-cash-flow';

export interface AgentMemo {
  workProductType: WorkProductType;
  markdown: string;
  html: string;
  output: AgentOutput | null;
  pdfUrl: string | null;
}

export interface RunHistoryEntry {
  id: string;
  workProductType: WorkProductType;
  status: string;
  modelVersion: string;
  promptVersion: string;
  publishedAt: Date | null;
  createdAt: Date;
  attemptCount: number;
  pdfUrl: string | null;
}

const FILE_BY_TYPE: Record<WorkProductType, string> = {
  'weekly-memo': 'latest-memo.md',
  'monthly-cash-flow': 'latest-cash-flow.md'
};

async function readMarkdown(fundSlug: string, type: WorkProductType): Promise<string | null> {
  const file = path.join(CONTENT_DIR, fundSlug, FILE_BY_TYPE[type]);
  try {
    return await readFile(file, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw err;
  }
}

function renderMarkdown(md: string): string {
  // Markdown is generated by an LLM and is therefore untrusted output:
  // sanitize the rendered HTML to defend against any injected
  // <script>, on* handlers, or other XSS payloads, then dangerously-
  // set the result via {@html} in the consuming component.
  marked.setOptions({ gfm: true, breaks: false });
  const html = marked.parse(md, { async: false }) as string;
  return DOMPurify.sanitize(html);
}

function pdfUrl(out: AgentOutput | null): string | null {
  if (!out?.pdfObjectPath) return null;
  const raw = out.pdfObjectPath;
  // Newer rows persist the public URL as "/api/agent/pdfs/<file>".
  // Older rows (pre object-storage) stored the bare object key
  // "/agent-pdfs/<file>"; rewrite those onto the api-server route.
  if (raw.startsWith('/api/')) return raw;
  if (raw.startsWith('/agent-pdfs/')) {
    return `/api/agent/pdfs/${raw.slice('/agent-pdfs/'.length)}`;
  }
  return raw;
}

async function latestSucceeded(
  fundSlug: string,
  type: WorkProductType
): Promise<AgentOutput | null> {
  const rows = await db
    .select()
    .from(agentOutputsTable)
    .where(
      and(
        eq(agentOutputsTable.fundSlug, fundSlug),
        eq(agentOutputsTable.workProductType, type),
        eq(agentOutputsTable.status, 'succeeded')
      )
    )
    // createdAt is always set; publishedAt is set on success but is the
    // intended sort key when present. Because we already filter by
    // status='succeeded' (which always sets publishedAt), this ordering
    // is unambiguous, with createdAt as a stable tie-breaker.
    .orderBy(desc(agentOutputsTable.publishedAt), desc(agentOutputsTable.createdAt))
    .limit(1);
  return rows[0] ?? null;
}

export async function loadMemo(
  fundSlug: string,
  type: WorkProductType
): Promise<AgentMemo | null> {
  const [markdown, output] = await Promise.all([
    readMarkdown(fundSlug, type),
    latestSucceeded(fundSlug, type)
  ]);
  if (!markdown) return null;
  return {
    workProductType: type,
    markdown,
    html: renderMarkdown(markdown),
    output,
    pdfUrl: pdfUrl(output)
  };
}

export async function loadRunHistory(fundSlug: string, limit = 8): Promise<RunHistoryEntry[]> {
  const rows = await db
    .select()
    .from(agentOutputsTable)
    .where(eq(agentOutputsTable.fundSlug, fundSlug))
    .orderBy(desc(agentOutputsTable.createdAt))
    .limit(limit);
  return rows.map((r) => ({
    id: r.id,
    workProductType: r.workProductType as WorkProductType,
    status: r.status,
    modelVersion: r.modelVersion,
    promptVersion: r.promptVersion,
    publishedAt: r.publishedAt,
    createdAt: r.createdAt,
    attemptCount: r.attemptCount,
    pdfUrl: pdfUrl(r)
  }));
}

export interface LatestWeeklyAcrossFunds {
  fundSlug: string;
  output: AgentOutput;
  excerptHtml: string;
  pdfUrl: string | null;
}

function firstParagraphHtml(markdown: string): string {
  // The structured prompt opens with "## Headline" + a single sentence,
  // then "## What changed" + a list. Surface the body of the section
  // AFTER the headline so the card excerpt does not duplicate the title.
  const lines = markdown.split('\n');
  const buf: string[] = [];
  let headingsSeen = 0;
  for (const line of lines) {
    const isH = line.startsWith('## ') || line.startsWith('# ');
    if (isH) {
      headingsSeen += 1;
      if (headingsSeen === 1 || headingsSeen === 2) continue; // skip Headline + open second section
      break; // hit the third heading -> stop
    }
    if (headingsSeen < 2) continue; // still inside the headline section
    buf.push(line);
    if (buf.join('\n').length > 360) break;
  }
  let md = buf.join('\n').trim();
  if (!md) {
    // Fallback for memos that don't follow the canonical heading pattern:
    // strip headings + thematic breaks and take the first ~360 chars.
    md = markdown
      .split('\n')
      .filter((l) => !l.startsWith('#') && l.trim() !== '---')
      .join('\n')
      .trim()
      .slice(0, 360);
  }
  if (!md) return '';
  return renderMarkdown(md);
}

function headlineFrom(markdown: string): string | null {
  const m = markdown.match(/^##\s+Headline\s*\n+([^\n]+)/m);
  return m ? m[1].trim() : null;
}

export async function loadLatestWeeklyAcrossFunds(
  fundSlugs: string[]
): Promise<LatestWeeklyAcrossFunds[]> {
  const results = await Promise.all(
    fundSlugs.map(async (slug) => {
      const memo = await loadMemo(slug, 'weekly-memo');
      if (!memo || !memo.output) return null;
      return {
        fundSlug: slug,
        output: memo.output,
        excerptHtml: firstParagraphHtml(memo.markdown),
        headline: headlineFrom(memo.markdown),
        pdfUrl: memo.pdfUrl
      } as LatestWeeklyAcrossFunds & { headline: string | null };
    })
  );
  return results
    .filter((r): r is LatestWeeklyAcrossFunds & { headline: string | null } => r !== null)
    .sort((a, b) => {
      const da = a.output.publishedAt ?? a.output.createdAt;
      const db_ = b.output.publishedAt ?? b.output.createdAt;
      return db_.getTime() - da.getTime();
    });
}
